### ISSUE TITLE
Uncolumnize

### ISSUE THREAD

**Issue by ghost** [adamwulf/Columnizer-jQuery-Plugin#148]
Is there a way to uncolumnize?

i.e for a responsive site is there a way to regenerate the columns for different screen sizes?

So for example I'd like on smaller devices only to display one column instead of two.
So on resize I had this:

if (s.width < 768){
		
				
$('.columns').columnize({ columns: 1, buildOnce: false });
		
} else {

$('.columns').columnize({ columns: 2, buildOnce: false });

}

Doesn't seem to work though.. any ideas?

**Comment by Regaddi** [comment]
That's like the dirtiest way to do that. Sorry for that post.

Please provide a sober API method to revert the changes.

This can be easily done by e.g. saving a DOM clone of the initial markup, when columnize() was called.

**Comment by adamwulf** [comment]
uncolumnizing is not widely requested, so its not a high priority for me to add into columnizer, especially because, as you mention, its very easy to implement on your own with a clone().

**Comment by adamwulf** [comment]
As a follow up - you're welcome to submit a pull request and/or fork to implement this.

**Comment by Regaddi** [comment]
@adamwulf See https://github.com/adamwulf/Columnizer-jQuery-Plugin/pull/206 ;)

**Comment by adamwulf** [comment]
awesome thanks - just merged it in :)

**Comment by Regaddi** [comment]
You're welcome :)
Glad to see it merged :)
