### ISSUE TITLE
Percentage widths for columns

### ISSUE THREAD

**Issue by matthew-dean** [adamwulf/Columnizer-jQuery-Plugin#174]
For a responsive site, I'm building in 3 columns. The issue: I cannot specify a percentage width for the column. I can specify the number of columns (3), BUT there's an additional behavior attached to that: columnizer distributes content equally amongst the columns. It would be nice if these were two separate options, one for "fill" vs. "distribute", and one for width, that was either pixel or percentage.

What I am trying to achieve:

1. Build 3 columns, 33.33% width
2. Put all content into the first column. If overflow, into second, then third.
3. On resize, re-measure and redistribute according to # 2.

**Comment by skittlecrack** [comment]
i am having trouble with this too. i simply want to columnize at 33.3%. no fixed height, no overflow rules.

**Comment by adamwulf** [comment]
@skittlecrack if you don't need fixed height for the columns, then {columns: 3} should work fine for you

**Comment by skittlecrack** [comment]
@adamwulf  {columns: 3} produces 33%. it seems like the plugin doesn't want to produce a decimal value

**Comment by adamwulf** [comment]
try {precise:true} (i'm looking at src lines ~ 80 ish). that may get you what you want. As I recall, in some browsers it would end up breaking that last column to another row b/c of rounding issues, which is why it defaults to floor().

**Comment by skittlecrack** [comment]
@adamwulf perfect, that was it. thank you!

**Comment by adamwulf** [comment]
glad it worked!
