### ISSUE TITLE
Radio inputs (with brackets in the name?)

### ISSUE THREAD

**Issue by LucanFahr** [adamwulf/Columnizer-jQuery-Plugin#188]
I am not sure if this problem exists for all radio inputs, or only for one with brackets in the name.

I have a radio that looks like this;

<input type="radio" name="fields[0]" value="m" /> Male
<input type="radio" name="fields[0]" value="f" /> Female

After columnizing the page, BOTH inputs have their value set to "m". In the page source it still says "m" and "f" separately.

**Comment by LucanFahr** [comment]
This seems to be a far deeper problem somewhere in jQuery - my apologies for posting it here. Ticket closed and I shall open another one on the jQuery site.

**Comment by adamwulf** [comment]
very strange indeed - if you can, please post the url of the jquery issue too
