### ISSUE TITLE
Please publish to NPM

### ISSUE THREAD

**Issue by asdcdow** [adamwulf/Columnizer-jQuery-Plugin#212]
I would like to stop having to support both Bower and NPM dependencies in my projects.  Since jQuery now [recommends](https://plugins.jquery.com/) publishing plugins to NPM, I'm now trying to move all of my projects to just use NPM.  This is the only jQuery plugin I still have that isn't on NPM. Please publish to NPM.

Thanks

**Comment by adamwulf** [comment]
kapow! https://www.npmjs.com/package/jquery-columnizer :)

hopefully that worked. it may or may not be my first use of npm ever.....

**Comment by asdcdow** [comment]
That worked perfectly.  Thanks!

**Comment by asdcdow** [comment]
You may want to also add 'jquery-plugin' as an additional keyword.  Since that is recommended by jQuery.  I assume it will make it easier for people to find your plugin.

**Comment by adamwulf** [comment]
done - thanks!
