### ISSUE TITLE
Form field values are blanked

### ISSUE THREAD

**Issue by Thunderscreech** [adamwulf/Columnizer-jQuery-Plugin#213]
Issue: When you .columnize either a POST or GET form, all form elements stop working.

To reproduce, create a form with the GET method (easiest to reproduce) and an action pointing anywhere and make an input of the checkbox type.  If you submit it, the URL will show the checkbox status.  Now put this into a DIV amd .columnize it and re-submit, the GET variable doesn't show up in the header.  POST is also broken.  Not sure what's happening, inspecting the element shows the same thing as before, same as the form.

**Comment by Thunderscreech** [comment]
One addition, it's only form elements in the first column that are inactive, the ones in the second column seem to work fine.

**Comment by Thunderscreech** [comment]
aaaaaand I figured out what's happening.  If the form is INSIDE the DIV, the columnize function is making a separate form for each column.  The workaround in my case is to put the form tags on the outside of the DIV being .columnized.  The bug here might be in how forms are handled within elements being columnized.  Making multiple forms where there was one has the effect of basically redacting any form elements in any column but the last one.  Hope this thread helps someone out in the meantime.

**Comment by adamwulf** [comment]
awesome - glad you got it sorted! another thing you can try is to use the 'dontsplit' class on the form element. that'll force the form to get put entirely into 1 column and will prevent it getting split up across columns.
