### ISSUE TITLE
Awkward Column Break Points

### ISSUE THREAD

**Issue by nickff** [adamwulf/Columnizer-jQuery-Plugin#214]
Hi Adam,

First of all, thanks for the great plugin!

Secondly, I'm using it here - http://www.vmdo.com/about.html - and noticing that the first column often breaks at an awkward point, but as soon as you resize the browser it becomes "smarter" and breaks to the second column at a more appropriate place.

Here's an example of the awkward break on page load:

![awkward](https://cloud.githubusercontent.com/assets/386558/18806096/fde94a26-81d4-11e6-8b08-f24fc07f81e3.png)

And then the better break just after resizing the browser window:

![good](https://cloud.githubusercontent.com/assets/386558/18806097/01ce00e6-81d5-11e6-9080-09ffbd24a1a9.png)

Any ideas on how to get it to break at that more appropriate juncture on page load? Let me know!

**Comment by adamwulf** [comment]
Is your script definitely running on page load and not before? If so, another thought would be to adjust the `accuracy` option to some low integer - maybe around 3 or 5. That'll affect the amount of text that's calculated when chopping text between columns.

**Comment by nickff** [comment]
@adamwulf worked like a charm. thanks so much, adam!!

**Comment by adamwulf** [comment]
glad to hear it!
