### ISSUE TITLE
Possible to preserve nested items?

### ISSUE THREAD

**Issue by uprise10** [adamwulf/Columnizer-jQuery-Plugin#216]
At the moment nested items are not preserved when splitting it into columns. See screenshot below:
<img width="1010" alt="screen shot 2016-12-20 at 11 45 16" src="https://cloud.githubusercontent.com/assets/1333461/21347643/d6f5cfb0-c6a9-11e6-89dc-c3a740a9ae71.png">

Now, the double bullets could be solved, but rather I'd like to have an option to preserve the nested items, so they stay together in their own column.

I couldn't find an option for it. Is there one, or do we have a feature request here? :-)

**Comment by adamwulf** [comment]
you could try adding the `dontsplit` class to the <li>. that'll keep the entire <li><ul/></li> as one single element and won't let it get split up

**Comment by uprise10** [comment]
Ah great! Must have overlooked that option. Thanks :)
