### ISSUE TITLE
long text, repeat the overflow method

### ISSUE THREAD

**Issue by pppws** [adamwulf/Columnizer-jQuery-Plugin#222]
hey there,

i have a super long text wich i want to columnize – the basics work smooth, but i struggle with the advanced implementation.

with the overflow method i 'crop' the text to a certain hight and display the remainder in a new `div` which also works like a charm. but the remainder is still too long so i'm trying to `overflow` the remainder as well. this is where i strunge and can't make it work.

is there a easy solution to this problem? are there any related questions already answered (which i did not find?)

cheers

**Comment by adamwulf** [comment]
Check out sample9.html. This example does something very similar - it has a very long piece of content, and progressively lays it out with overflow: over multiple pages. It should give you a better idea on how to implement what you're looking for.

**Comment by pppws** [comment]
but sampe9.html isn't using overflow at all?

i'm trying to achive something like this:
https://jsfiddle.net/5bscdc81/

i can get the first to section to work, but i can't figure out how to columnize the remainder of section2.

**Comment by adamwulf** [comment]
Look again, it uses the overflow option on line 44 of sample9.html

**Comment by pppws** [comment]
on here https://welcome.totheinter.net/columnizer-jquery-plugin/ i don't find sample9.html and 
on this one: https://welcome.totheinter.net/autocolumn/sample9.html there is no overflow.

but i think you mean sample there is a overflow on line 44. will check it out. thanks!

**Comment by pppws** [comment]
made it work! thanks – sorry for the confusion about the samples!

**Comment by adamwulf** [comment]
ah - I'll have to update the sample list on the site. glad you got it working!
