### ISSUE TITLE
Padding added to top of defined columns (or ability to float multi-column-spanned image)

### ISSUE THREAD

**Issue by akeith2002** [adamwulf/Columnizer-jQuery-Plugin#73]
Hi there.

I am looking to have a 4 column layout of text but I want to float an image in the upper right spanning 3 of those four columns. I thought the easiest way to do this might be the ability to specify which columns need padding and how much and to render that but then still render all of the columns the same height.

What are your thoughts on this? Is there a current way to do it? Is someone else asking for the same ability but just in a different way? I'd be willing to throw some $$ down if some one could implement this for me. Been searching the inner-webs high and low for a way to do this and I have been unable to come up with a good solution (until css regions are fully supported).

Thanks!

**Comment by kamalakkanni** [comment]
Thanks adam,can you please provide an example for it.
